#!/bin/bash
# ![](https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/XXX/YYY.jpg)

TOP="${HOME}/Documents/Obsidian/Obsidian-Media-Vault/Books"

[ -d "${TOP}" ] || {
  echo "$TOP does not exist or is not a directory. Exiting."
  exit 1
}

cd "${TOP}"

rm -f /tmp/notfound
touch /tmp/notfound
rm -f /tmp/missingart
touch /tmp/missingart
for book in */*.md
do
  [ "${book}" == "*/*.md" ] && continue
  [ -f ${book} ] || {
    echo "${book} does not exist. Skipping."
    continue
  }
  grep "/assets/bookcovers/" ${book} > /dev/null || {
    grep "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/" ${book} > /dev/null || {
      echo "${book}: Pattern not found. Skipping." | tee -a /tmp/notfound
      continue
    }
    imgurl=`grep "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/" ${book}`
    imgpath=`echo ${imgurl} | awk -F '/' ' { print $8 } ' | sed -e 's/^ *//' -e 's/ *$//'`
    imgfile=`echo ${imgurl} | awk -F '/' ' { print $9 } ' | awk -F ')' ' { print $1 } ' | sed -e 's/^ *//' -e 's/ *$//'`
#   echo "imgpath = ${imgpath}"
#   echo "imgfile = ${imgfile}"
    # Replace book cover art link for this book
    if [ -f ../assets/bookcovers/${imgpath}/${imgfile} ]
    then
      cat ${book} | sed -e "s%https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books%../..%" > /tmp/book$$
      cp /tmp/book$$ ${book}
      rm -f /tmp/book$$
    else
      echo "Cover art does not exist for ${imgpath}/${imgfile}" | tee -a /tmp/missingart
    fi
  }
done
